version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: shadowsocks/android-ndk-go # 确保这是你构建的包含NDK的镜像
    environment:
      JVM_OPTS: -Xmx3500m
      GRADLE_OPTS: -Dorg.gradle.workers.max=1 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy="in-process"
    steps:
      - checkout
      - run:
          name: Print NDK Path for Debugging
          command: |
            echo "ANDROID_HOME is set to $ANDROID_HOME"
            ls $ANDROID_HOME
            echo "-----------------------------------------------------------------------"
            export ANDROID_NDK_HOME=$ANDROID_HOME$ANDROID_NDK_HOME
            echo "ANDROID_NDK_HOME is set to $ANDROID_NDK_HOME"
            echo "-----------------------------------------------------------------------"
            ls $ANDROID_NDK_HOME
      - run: git submodule update --init --recursive
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}
      - restore_cache:
          key: go-{{ checksum "app/src/main/go/v2ray-plugin/go.sum" }}
      - run:
          name: Run Build and Tests
          command: ./gradlew assembleDebug check --info
      - save_cache:
          paths:
            - ~/go
          key: go-{{ checksum "app/src/main/go/v2ray-plugin/go.sum" }}
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android/build-cache
          key: jars-{{ checksum "build.gradle.kts" }}
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_artifacts:
          path: app/build/reports
          destination: reports