version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30 # 使用官方 CircleCI Android 镜像
    environment:
      JVM_OPTS: -Xmx3500m
      GRADLE_OPTS: -Dorg.gradle.workers.max=1 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy="in-process"
    steps:
      - checkout
      - run:
          name: Install Android NDK
          command: |
            echo "Installing Android NDK..."
            sdkmanager --install "ndk;21.3.6528147" # 安装指定版本的 NDK
            export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/21.3.6528147
            echo "ANDROID_NDK_HOME is set to $ANDROID_NDK_HOME"
            ls -la $ANDROID_NDK_HOME
      - run:
          name: Print SDK Path for Debugging
          command: |
            echo "ANDROID_HOME is set to $ANDROID_HOME"
            ls -la $ANDROID_HOME
            echo "-----------------------------------------------------------------------"
            echo "ANDROID_NDK_HOME is set to $ANDROID_NDK_HOME"
            echo "-----------------------------------------------------------------------"
            ls -la $ANDROID_NDK_HOME
      - run: git submodule update --init --recursive
      - restore_cache:
          keys:
            - jars-{{ checksum "build.gradle.kts" }}
            - jars-
      - restore_cache:
          keys:
            - go-{{ checksum "app/src/main/go/v2ray-plugin/go.sum" }}
            - go-
      - run:
          name: Run Build and Tests
          command: |
            chmod +x ./gradlew
            ./gradlew assembleDebug check --info
      - save_cache:
          paths:
            - ~/go
          key: go-{{ checksum "app/src/main/go/v2ray-plugin/go.sum" }}
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android/build-cache
          key: jars-{{ checksum "build.gradle.kts" }}
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_artifacts:
          path: app/build/reports
          destination: reports
